### ISSUE TITLE
[drone] take a list of repositories for export and migrate

### ISSUE THREAD

**Issue by jimsheldon** [harness/harness-migrate#56]
`harness-migrate drone export` and `harness-migrate drone migrate` should support taking a list of repositories, rather than pulling all repositories from the provided drone namespace.

This will help with demos and test migrations, or when the user only wants to export/migrate a subset of repos.

The default behavior should still be to export/migrate everything in the namespace.

It should be a comma-separated list, or maybe read from a file (or maybe support both?).

Example:

```
harness-migrate drone migrate --namespace example --repository-list repo-one,repo-two,another-repo
```

**Comment by eoinmcafee00** [comment]
PR raised: https://github.com/harness/harness-migrate/pull/58/files

**Comment by eoinmcafee00** [comment]
This can be closed?

**Comment by jimsheldon** [comment]
Yup! thanks
