### ISSUE TITLE
[drone] pipeline yaml must escape `${}`

### ISSUE THREAD

**Issue by jimsheldon** [harness/harness-migrate#57]
When using converted yaml in terraform, `${}` variables must be escaped.

For example, `${DRONE_REPO_NAME]` must become `$${DRONE_REPO_NAME}`

**Comment by eoinmcafee00** [comment]
@jimsheldon - This change should only applied if we are exporting to Terraform, should we add a flag? Or how do we want to handle this?

**Comment by jimsheldon** [comment]
@eoinmcafee00 it is only needed when the `toYaml` function is used when generating terraform configurations https://github.com/harness/harness-migrate/blob/master/cmd/terraform/terraform.go#L106

Maybe we can add something in that function that will translate `${` to `$${`?
