### ISSUE TITLE
[drone] support disabling TLS for custom URLs

### ISSUE THREAD

**Issue by jimsheldon** [harness/harness-migrate#73]
We need the equivalent support for these drone server settings

https://docs.drone.io/server/reference/drone-github-skip-verify/
https://docs.drone.io/server/reference/drone-gitlab-skip-verify/
https://docs.drone.io/server/reference/drone-stash-skip-verify/

**Comment by jimsheldon** [comment]
Adding initial support for GitHub Enterprise in #74

**Comment by eoinmcafee00** [comment]
Hey @jimsheldon
Looks lie you've done this already?

**Comment by jimsheldon** [comment]
Fixed in #86
